# Generated by Django 4.1.1 on 2022-09-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.CharField(max_length=1000),
        ),
    ]
